  chatqna-xeon-backend-server:
    image: ${REGISTRY:-opea}/chatqna:${TAG:-latest}
#    container_name: megaservice
#    depends_on:
#      redis-vector-db:
#        condition: service_started
#      dataprep-redis-service:
#        condition: service_healthy
#      tei-embedding-service:
#        condition: service_started
#      retriever:
#        condition: service_started
#      tei-reranking-service:
#        condition: service_started
#      vllm-service:
#        condition: service_healthy
    ports:
      - "8888:8888"
    ipc: host
    restart: always